prueba/asignaturas/urls.py


from django.urls import path
from .views import aginatura_, eliminar_asignatura,registar_asignatura, clases

app_name = 'agnatura'

urlpatterns = [
    path('',aginatura_.as_view(),name = 'asignatura'),
    path('clase/',clases.as_view(),name = 'clase'),
    path('registrar-asignatura/', registar_asignatura),
    path('eliminar/asignatura/<int:pk>',eliminar_asignatura)
    # path('', estudiant, name = 'Estudiante'),
]

prueba/estudiante/urls.py


from django.urls import path
from .views import estudiant, eliminar_estudiante,registar_estudiante

app_name = 'estudiante'

urlpatterns = [
    path('',estudiant.as_view(),name = 'Estudiante'),
    path('registrar-estudiante/', registar_estudiante),
    path('eliminar/estudiante/<int:pk>',eliminar_estudiante)
    # path('', estudiant, name = 'Estudiante'),
]

prueba/prueba/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('estudiante/', include('estudiante.urls')),
    path('asignatura/', include('asignaturas.urls')),
]

prueba/asignaturas/models.py
from django.db import models
from estudiante.models import estudiante

class asignatura(models.Model):
    nombre = models.CharField(max_length=100)
    salon = models.CharField(max_length=10)
    horario = models.CharField(max_length=200)
    id_profesor = models.IntegerField()

class clase(models.Model):
    id_estudiante = models.ForeignKey(estudiante, on_delete=models.CASCADE)
    id_signatura = models.ForeignKey(asignatura, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id_signatura.nombre)

prueba/estudiante/models.py
from django.db import models


class estudiante(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    identificacion = models.IntegerField(primary_key=True)
    correo = models.EmailField(max_length=200, null=True, blank=True)
    p_academico = models.CharField(max_length=100)

prueba/asignaturas/views.py

from django.shortcuts import render,redirect
from .models import asignatura, clase,estudiante
from django.views.generic import CreateView

# def estudiant(request):
#     data = {
#         'titulo': 'Gestor estudiante',
#         'estudiante': estudiante.objects.all()
#     }
#     return render(request,'estudiante.html',data)

class aginatura_(CreateView):
    model = asignatura
    template_name = 'asignatura.html'
    fields ='__all__'

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex['titulo'] = 'Gestion asignatura'
        contex['asignatura'] = asignatura.objects.all()
        return contex



def registar_asignatura(request):
    nombre = request.POST['txtNombre']
    salon = request.POST['txtSalon']
    horario = request.POST['txtHoratio']
    id_profesor = request.POST['nunIdeprofesor']
    estudiant = asignatura.objects.create(nombre=nombre, salon=salon,horario=horario,id_profesor=id_profesor)

    return redirect('agnatura:asignatura')

def eliminar_asignatura(request,pk):
    asignatura.objects.filter(pk=pk).delete()
    return redirect('agnatura:asignatura')

# clases
class clases(CreateView):
    model = clase
    template_name = 'curso.html'
    fields ='__all__'

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex['titulo'] = 'Gestion clases'
        contex['curso'] = clase.objects.all()
        contex['estudiante'] = estudiante.objects.all()
        contex['asignatura'] = asignatura.objects.all()
        return contex

def registar_clase(request):
    nombre = request.POST['txtNombre']
    salon = request.POST['txtSalon']
    horario = request.POST['txtHoratio']
    id_profesor = request.POST['nunIdeprofesor']
    estudiant = clase.objects.create(nombre=nombre, salon=salon,horario=horario,id_profesor=id_profesor)

    return redirect('agnatura:asignatura')

def eliminar_clase(request,pk):
    clase.objects.filter(pk=pk).delete()
    return redirect('agnatura:asignatura')

prueba/estudiante/views.py
from django.shortcuts import render,redirect
from .models import estudiante
from django.views.generic import CreateView

# def estudiant(request):
#     data = {
#         'titulo': 'Gestor estudiante',
#         'estudiante': estudiante.objects.all()
#     }
#     return render(request,'estudiante.html',data)

class estudiant(CreateView):
    model = estudiante
    template_name = 'estudiante.html'
    fields ='__all__'

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex['titulo'] = 'Gestion estudiante'
        contex['estudiante'] = estudiante.objects.all()
        return contex

def registar_estudiante(request):

    nombre = request.POST['txtNombre']
    print(nombre)
    apellido = request.POST['txtApellido']
    identificacion = request.POST['numIdentificacion']
    email = request.POST['txtEmail']
    programa = request.POST['txtPrograma']
    estudiant = estudiante.objects.create(nombre=nombre, apellido=apellido,identificacion=identificacion,
                                          correo=email,p_academico=programa)

    return redirect('estudiante:Estudiante')

def eliminar_estudiante(request,pk):
    estudiante.objects.filter(pk=pk).delete()
    return redirect('estudiante:Estudiante')

prueba/asignaturas/templates/asignatura.html
{% extends 'home.html' %}
{% block content %}
    <thead>

    </thead>
    <tbody>
    <div class="row">
        <div class="col-md-4">
            <h2>Crear asignatura</h2>
            <form id="formulario_asignatura" action="/asignatura/registrar-asignatura/" method="POST">{% csrf_token %}
                <div class="mb-3">
                    <div class="input-group">
                        <div class="input-group-text">Nombre</div>
                        <input type="text" class="form-control" name="txtNombre" id="txtNombre" minlength="3" maxlength="100" autofocus>
                    </div>
                </div>
                <div class="mb-3">
                    <div class="input-group">
                        <div class="input-group-text">Salón</div>
                        <input type="text" class="form-control" name="txtSalon" id="txtSalon" minlength="3" maxlength="100">
                    </div>
                </div>
                <div class="mb-3">
                    <div class="input-group">
                        <div class="input-group-text">Horario</div>
                        <input type="text" class="form-control" name="txtHoratio" id="txtHoratio"">
                    </div>
                </div>
                <div class="mb-3">
                    <div class="input-group">
                        <div class="input-group-text">Id profesor</div>
                        <input type="number" class="form-control" name="nunIdeprofesor" id="nunIdeprofesor"minlength="3" maxlength="200">

                    </div>
                </div>
                <button type="submit" class="btn btn-success">Crear nueva asignatura</button>
            </form>
        </div>
        <div class="col-md-8">
            <h2>Listado asignaturas</h2>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Salón</th>
                        <th scope="col">Horario</th>
                        <th scope="col">Id profesor</th>
                        <th scope="col">Opcines</th>
                    </tr>
                    </thead>
                    {% for asig in asignatura %}
                        <tr>
                            <td>{{ asig.pk }}</td>
                            <td>{{ asig.nombre }}</td>
                            <td>{{ asig.salon }}</td>
                            <td>{{ asig.horario }}</td>
                            <td>{{ asig.id_profesor }}</td>
                            <td>
{#                                <a href="eliminar/estudiante/{{ estu.pk }}" class="btn btn-success">agregar</a>#}
                                <a href="eliminar/asignatura/{{ asig.pk }}" class="btn btn-danger">eliminar</a>
                            </td>
                        </tr>

                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    </tbody>
{% endblock %}

prueba/asignaturas/templates/curso.html
{% extends 'home.html' %}
{% block content %}
    <thead>
    </thead>
    <tbody>
    <div class="row">
        <div class="col-md-4">
            <h2>Asignar curso</h2>
            <form id="formulario_asignatura" action="/asignatura/asignar-curso/" method="POST">{% csrf_token %}
                <div class="mb-3">
                <label class="form-label">Asignatura</label>
                    <div class="input-group">
                            <select class="form-select" aria-label="Default select example">}
                                 {% for curo in asignatura %}
                                <option selected>{{ curo.nombre }}</option>
                                {% endfor %}
                            </select>
                    </div>
                <label class="form-label">Estudiante</label>
                <div class="input-group">
                            <select class="form-select" aria-label="Default select example">}
                                 {% for curo in estudiante %}
                                <option selected>{{ curo.pk }} {{ curo.nombre }} {{ curo.apellido}}</option>
                                {% endfor %}
                            </select>
                    </div>
                </div>

                <button type="submit" class="btn btn-success">Crear nuevo curso</button>
            </form>
        </div>
        <div class="col-md-8">
            <h2>Listado asignaturas</h2>



            <div class="card">

                <div class="card-body">
                    {% for cueso in curso %}
                       <p>{{ cueso }} {{ cueso.id_estudiante.nombre}}</p>
                     {% endfor %}
                </div>

            </div>

        </div>
    </div>
    </div>
    </tbody>
{% endblock %}

prueba/estudiante/templates/estudiante.html
{% extends 'home.html' %}
{% block content %}
    <thead>

    </thead>
    <tbody>
    <div class="row">
        <div class="col-md-4">
            <h2>Crear estudiante</h2>
            <form id="formulario_estudiante" action="/estudiante/registrar-estudiante/" method="POST">{% csrf_token %}
                <div class="mb-3">
                    <div class="input-group">
                        <div class="input-group-text">Nombre</div>
                        <input type="text" class="form-control" name="txtNombre" id="txtNombre" minlength="3" maxlength="100" autofocus>
                    </div>
                </div>
                <div class="mb-3">
                    <div class="input-group">
                        <div class="input-group-text">Apellido</div>
                        <input type="text" class="form-control" name="txtApellido" id="txtApellido" minlength="3" maxlength="100">
                    </div>
                </div>
                <div class="mb-3">
                    <div class="input-group">
                        <div class="input-group-text">Identificacion</div>
                        <input type="number" class="form-control" name="numIdentificacion" id="numIdentificacion">
                    </div>
                </div>
                <div class="mb-3">
                    <div class="input-group">
                        <div class="input-group-text">Correo</div>
                        <input type="email" class="form-control" name="txtEmail" id="txtEmail"minlength="3" maxlength="200">

                    </div>
                </div>
                <div class="mb-3">
                    <div class="input-group">
                        <div class="input-group-text">Programa academmico</div>
                        <input type="text" class="form-control" name="txtPrograma" id="txtPrograma" minlength="3" maxlength="100">
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Crear nuevo estudiante</button>
            </form>
        </div>
        <div class="col-md-8">
            <h2>Listado estudiantes</h2>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Apellido</th>
                        <th scope="col">Identificacion</th>
                        <th scope="col">Correo</th>
                        <th scope="col">Programa académico</th>
                        <th scope="col">Opcines</th>
                    </tr>
                    </thead>
                    {% for estu in estudiante %}
                        <tr>
                            <td>{{ estu.nombre }}</td>
                            <td>{{ estu.apellido }}</td>
                            <td>{{ estu.identificacion }}</td>
                            <td>{{ estu.correo }}</td>
                            <td>{{ estu.p_academico }}</td>
                            <td>
{#                                <a href="eliminar/estudiante/{{ estu.pk }}" class="btn btn-success">agregar</a>#}
                                <a href="eliminar/estudiante/{{ estu.pk }}" class="btn btn-danger">eliminar</a>
                            </td>
                        </tr>

                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    </tbody>
    <script>
    const $formulario_estudiante = document.getElementById('formulario_estudiante');
    const $numIdentificacion = document.getElementById('numIdentificacion');

    (function (){
         $formulario_estudiante.addEventListener('submit', function (e){
         let identificacion = parseInt($numIdentificacion.value());
         console.log(identificacion);
         {% for estu in estudiante %}
             console.log({{ estu.identificacion }})
             if (identificacion === {{ estu.identificacion }}){
                 alert('El documento',{{ estu.identificacion }},' ya se encuentra registrado')
                 e.preventDefault();
             }
         {% endfor %}
    });
    }());
    </script>
{% endblock %}

prueba/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ titulo }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
{% include 'navbar.html' %}
<div class="p-5">
{% block content %}
{% endblock %}
</div>

</body>
</html>

prueba/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <h1 class="navbar-brand">{{ titulo }}</h1>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'estudiante:Estudiante' %}">Estudiante</a>
        <a class="nav-link" href="{% url 'agnatura:asignatura' %}">Asignatura</a>
        <a class="nav-link" href="{% url 'agnatura:clase' %}">Curso</a>
      </div>
    </div>
  </div>
</nav>